package crypto

import (
	"sync"
	"testing"
)

// resetKeyForTest resets the package-level key state so each test can drive
// a different key-sourcing tier. Only safe within this package's own test file.
func resetKeyForTest(key string) {
	encryptionKey = key
	KeyIsAutoGenerated = false
	keyOnce = sync.Once{}
}

func TestEncryptDecryptRoundtrip(t *testing.T) {
	t.Setenv("TM_ENCRYPTION_KEY", "12345678901234567890123456789012")
	resetKeyForTest("")

	plaintext := "my-bearer-token-abc123"
	ciphertext, err := Encrypt(plaintext)
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}
	if ciphertext == plaintext {
		t.Fatal("ciphertext should not equal plaintext")
	}

	result, err := Decrypt(ciphertext)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if result != plaintext {
		t.Errorf("got %q, want %q", result, plaintext)
	}
}

func TestEncryptProducesUniqueOutputs(t *testing.T) {
	// AES-GCM uses a random nonce; same plaintext must produce different ciphertext.
	const key = "12345678901234567890123456789012"
	t.Setenv("TM_ENCRYPTION_KEY", key)

	resetKeyForTest("")
	c1, err := Encrypt("token")
	if err != nil {
		t.Fatalf("first Encrypt: %v", err)
	}

	resetKeyForTest(key) // keep key but reset Once so Encrypt runs the full path again
	c2, err := Encrypt("token")
	if err != nil {
		t.Fatalf("second Encrypt: %v", err)
	}

	if c1 == c2 {
		t.Error("expected unique ciphertext due to random nonce, got identical output")
	}
}

func TestDecryptWrongKeyFails(t *testing.T) {
	t.Setenv("TM_ENCRYPTION_KEY", "12345678901234567890123456789012")
	resetKeyForTest("")
	ciphertext, err := Encrypt("secret-payload")
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}

	// Switch to a different key before decrypting.
	t.Setenv("TM_ENCRYPTION_KEY", "aaaabbbbccccddddeeeeffff00001111")
	resetKeyForTest("")
	_, err = Decrypt(ciphertext)
	if err == nil {
		t.Fatal("expected decryption to fail with wrong key, got nil error")
	}
}

func TestKeyFromEnvVar(t *testing.T) {
	const key = "abcdefghijklmnopqrstuvwxyz123456"
	t.Setenv("TM_ENCRYPTION_KEY", key)
	resetKeyForTest("")

	got := getKey()
	if got != key {
		t.Errorf("getKey() = %q, want %q", got, key)
	}
	if KeyIsAutoGenerated {
		t.Error("KeyIsAutoGenerated should be false when env var is set")
	}
}

func TestKeyIsAutoGeneratedFlag(t *testing.T) {
	// Unset env var and point key file to a nonexistent path so tier 3 runs.
	t.Setenv("TM_ENCRYPTION_KEY", "")
	t.Setenv("TM_DB_PATH", t.TempDir()+"/nonexistent.db")
	resetKeyForTest("")

	getKey()
	if !KeyIsAutoGenerated {
		t.Error("KeyIsAutoGenerated should be true when no env var or key file exists")
	}
}

func TestDecryptInvalidBase64Fails(t *testing.T) {
	t.Setenv("TM_ENCRYPTION_KEY", "12345678901234567890123456789012")
	resetKeyForTest("")

	_, err := Decrypt("not-valid-base64!!!")
	if err == nil {
		t.Fatal("expected error for invalid base64 input")
	}
}
