package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"sync"
)

var (
	encryptionKey      string
	KeyIsAutoGenerated bool
	keyOnce            sync.Once
)

// getKey returns the 32-byte AES key via a 3-tier priority:
//  1. TM_ENCRYPTION_KEY env var (must be exactly 32 ASCII bytes)
//  2. Key file adjacent to the DB (derived from TM_DB_PATH)
//  3. Auto-generated random key (written to the key file, warned in logs)
func getKey() string {
	keyOnce.Do(func() {
		if k := os.Getenv("TM_ENCRYPTION_KEY"); len(k) == 32 {
			encryptionKey = k
			return
		}

		dbPath := os.Getenv("TM_DB_PATH")
		if dbPath == "" {
			dbPath = "./traefik-manager.db"
		}
		keyFile := filepath.Join(filepath.Dir(dbPath), ".tm_encryption_key")

		if data, err := os.ReadFile(keyFile); err == nil && len(data) == 32 {
			encryptionKey = string(data)
			return
		}

		// Auto-generate a random 32-hex-char key
		raw := make([]byte, 16)
		if _, err := io.ReadFull(rand.Reader, raw); err != nil {
			log.Fatalf("crypto/rand unavailable: %v", err)
		}
		encryptionKey = hex.EncodeToString(raw)
		KeyIsAutoGenerated = true

		_ = os.WriteFile(keyFile, []byte(encryptionKey), 0600)

		log.Println("WARNING: TM_ENCRYPTION_KEY not set. Auto-generated a random key saved to", keyFile)
		log.Println("WARNING: If this file is lost, all stored cluster credentials will become unreadable.")
	})
	return encryptionKey
}

// Encrypt encodes plaintext to a base64 AES-GCM ciphertext.
func Encrypt(plaintext string) (string, error) {
	key := getKey()

	block, err := aes.NewCipher([]byte(key))
	if err != nil {
		return "", err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err = io.ReadFull(rand.Reader, nonce); err != nil {
		return "", err
	}

	ciphertext := gcm.Seal(nonce, nonce, []byte(plaintext), nil)
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

// Decrypt decodes a base64 AES-GCM ciphertext back to plaintext.
func Decrypt(cryptoText string) (string, error) {
	key := getKey()

	ciphertext, err := base64.StdEncoding.DecodeString(cryptoText)
	if err != nil {
		return "", err
	}

	block, err := aes.NewCipher([]byte(key))
	if err != nil {
		return "", err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	nonceSize := gcm.NonceSize()
	if len(ciphertext) < nonceSize {
		return "", errors.New("ciphertext too short")
	}

	nonce, ciphertext := ciphertext[:nonceSize], ciphertext[nonceSize:]
	plaintext, err := gcm.Open(nil, []byte(nonce), ciphertext, nil)
	if err != nil {
		return "", fmt.Errorf("decryption failed. Wrong TM_ENCRYPTION_KEY? %v", err)
	}

	return string(plaintext), nil
}
