package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/noovastack/traefik-manager/internal/api"
	"github.com/noovastack/traefik-manager/internal/crypto"
	"github.com/noovastack/traefik-manager/internal/db"
	"github.com/noovastack/traefik-manager/internal/provider/k8s"
)

func main() {
	kubeconfig := flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
	flag.Parse()

	addr := env("TM_ADDR", ":8080")

	// 1. Initialize SQLite Database
	db.InitDB()
	log.Println("Database initialized successfully")

	// 2. Warn loudly if the encryption key was auto-generated
	if crypto.KeyIsAutoGenerated {
		log.Println("WARNING: Running with an auto-generated encryption key.")
		log.Println("WARNING: Set TM_ENCRYPTION_KEY to a stable 32-byte value to avoid losing cluster credentials on restart.")
	}

	// 3. Initialize Provider Manager
	providerType := env("TM_PROVIDER", "kubernetes")

	if providerType != "kubernetes" {
		log.Fatalf("unsupported TM_PROVIDER: %q (only 'kubernetes' is supported)", providerType)
	}

	localClient, err := k8s.NewClient(*kubeconfig)
	if err != nil {
		log.Fatalf("failed to initialize Kubernetes local client: %v", err)
	}

	kManager := k8s.NewManager(localClient)
	log.Println("Kubernetes Local Manager initialized successfully")

	// Rebuild remote clusters from the database on startup
	clusters, dbErr := db.GetClusters()
	if dbErr != nil {
		log.Fatalf("failed to read clusters from sqlite: %v", dbErr)
	}

	loadedCount := 0
	for _, c := range clusters {
		token, cryptoErr := crypto.Decrypt(c.EncryptedToken)
		if cryptoErr != nil {
			log.Printf("[ERR] Failed to decrypt token for cluster %q. Did TM_ENCRYPTION_KEY change? Skipping.", c.Name)
			continue
		}

		caCert := ""
		if c.EncryptedCACert != "" {
			caCert, cryptoErr = crypto.Decrypt(c.EncryptedCACert)
			if cryptoErr != nil {
				log.Printf("[ERR] Failed to decrypt CA cert for cluster %q. Skipping.", c.Name)
				continue
			}
		}

		if loadErr := kManager.AddCluster(c.ID, c.Name, c.ServerURL, token, caCert); loadErr != nil {
			log.Printf("[ERR] Failed to connect to remote cluster %q: %v", c.Name, loadErr)
			continue
		}
		loadedCount++
	}
	log.Printf("Loaded %d remote cluster(s) from SQLite", loadedCount)

	// 4. HTTP server
	router := api.NewRouter(kManager)

	if err := serveStaticFiles(router.(*chi.Mux), "dist"); err != nil {
		log.Printf("UI static files not found, serving API only (%v)", err)
	}

	srv := &http.Server{
		Addr:         addr,
		Handler:      router,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		log.Printf("server listening on %s", addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("server error: %v", err)
		}
	}()

	<-quit
	log.Println("shutting down gracefully...")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		log.Fatalf("shutdown error: %v", err)
	}
	log.Println("server stopped")
}

func env(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	fmt.Printf("using default for %s=%s\n", key, fallback)
	return fallback
}

func serveStaticFiles(r *chi.Mux, publicDir string) error {
	workDir, _ := os.Getwd()
	filesDir := filepath.Join(workDir, publicDir)

	if _, err := os.Stat(filesDir); os.IsNotExist(err) {
		return err
	}

	fs := http.FileServer(http.Dir(filesDir))

	r.Get("/*", func(w http.ResponseWriter, req *http.Request) {
		path := filepath.Join(filesDir, req.URL.Path)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			http.ServeFile(w, req, filepath.Join(filesDir, "index.html"))
			return
		}
		fs.ServeHTTP(w, req)
	})

	log.Printf("Serving static assets from %s", filesDir)
	return nil
}
